Repository spyder-ide/spyder-website, pull requests merged in 2024-10, with the labels that each got.

#23 Change command `vite` to `npx vite` to try to fix an error in deployment
  package.json
Labels: bug

#24 Remove `devDependencies` and only leave `dependencies` in `package.json`
  package-lock.json
  package.json
Labels: bug

#26 Change font weight for list items in blog from regular to light
  src/lib/blocks/Post.svelte
Labels: bug

#25 Add blog post announcing Spyder 6.0 release
  src/routes/blog/release-spyder-6.0.0/+page.md
Labels: Blog Post

#13 Add new About page with project details and team members
  .gitignore
  package-lock.json
  package.json
  src/lib/blocks/ContributorBlock.svelte
  src/lib/blocks/Header.svelte
  src/lib/components/ContributorCard.svelte
  src/lib/config/index.js
  src/routes/about/+page.js
  src/routes/about/+page.svelte
  static/assets/authors/camgerlach/pic.webp
  tailwind.config.js
Labels: enhancement

#30 Fix titles for pages which are missing them
  src/routes/about/+page.svelte
  src/routes/download/+page.svelte
Labels: bug

#28 Add title to comparison section in the home page and improve its graphic
  src/lib/blocks/ContentBlock.svelte
  src/lib/blocks/Hero.svelte
  src/routes/+page.js
  src/routes/+page.svelte
  static/assets/media/banner.svg
Labels: enhancement
