Repository spyder-ide/spyder-website, pull requests merged in 2024-09, with the labels that each got.

#3 Fix issue with video player controls and page titles
  src/lib/blocks/Blog.svelte
  src/lib/components/VideoPlayer.svelte
  src/routes/+layout.svelte
Labels: bug

#5 Fix Windows and macOS download URLs
  src/lib/config/index.js
Labels: bug

#14 Support separate alt text and captions in Markdown content
  package-lock.json
  package.json
  src/app.css
  src/lib/content/code-analysis.md
  src/lib/content/conda.md
  src/lib/content/developer-tools.md
  src/lib/content/matplotlib.md
  src/lib/content/numpy.md
  src/lib/content/pandas.md
  src/lib/content/projects.md
  src/lib/content/search.md
  src/lib/content/sympy.md
  svelte.config.js
  tailwind.config.js
Labels: bug

#6 Add blog post on Spyder's SciPy 2024 IDE UX BoF
  src/routes/blog/ide-ux-bof-scipy-2024/+page.md
  src/routes/blog/ide-ux-bof-scipy-2024/scipy-2024-bof-ide-ui-ux.jpg
Labels: Blog Post

#16 Add RSS feed to the blog
  src/lib/blocks/Blog.svelte
  src/lib/blocks/Footer.svelte
  src/lib/components/Button.svelte
  src/lib/config/index.js
  src/lib/utils/index.js
  src/routes/blog/feed.xml/+server.js
Labels: bug, enhancement

#19 Fix improper canonical URLs for OG meta tags
  .gitignore
  src/app.html
  src/lib/blocks/Blog.svelte
  src/lib/blocks/Post.svelte
  src/lib/components/Metadata.svelte
  src/routes/+page.svelte
  src/routes/blog/+page.svelte
  src/routes/blog/[page]/+page.svelte
Labels: enhancement
